name: Release

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent

      - name: Show semver output
        run: |
          cat <<EOF
          current: ${{ steps.semver.outputs.current }}
          next: ${{ steps.semver.outputs.next }}
          bump: ${{ steps.semver.outputs.bump }}
          EOF

      - name: Tag release
        if: ${{ steps.semver.outputs.bump != '' }}
        run: |
          git tag "${{ steps.semver.outputs.next }}"
          git push --tags

