name: Run git diff
on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: Run git diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Show diffs
        run: |
          pwd
          ls -A
          git --version
          git status
          git rev-parse HEAD
          git log
          git diff --name-only HEAD^..HEAD
