name: Can we create tag?

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: test if ghcli is available
        run: |
          gh help

      - name: test if we can create and push a tag
        run: |
          git tag -f example-tag
          git push --tags
