name: Test variable access

on:
  pull_request:
  push:

jobs:
  job1:
    environment: testenv
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF
          ${{ vars }}
          EOF
      - run: |
          touch testfile
  job2:
    runs-on: ubuntu-latest
    needs:
    - job1
    steps:
    - run: |
        ls -A
